main: me.venomouspenguin.antcraft.creative.core.Main
version: 1.0.1
authors: [SavagePenguins]
name: Antcraft-Roleplay

commands:
  roleplay:
    aliases: [rp]
    description: The roleplay command
permissions:
  antcraft.user.roleplay:
    description: The perm to access normal commands
    default: false
  antcraft.staff.roleplay.admin:
    description: The perm to access admin commands
    default: false
  antcraft.staff.roleplay.admin.chat:
    description: The perm to toggle on and off roleplay spy
    default: false